fastlane_version "2.16.0"

default_platform :ios

platform :ios do

	desc "Builds the framework"
	lane :build do
		xcodebuild(
			workspace: "KJHUIKit.xcworkspace",
		    scheme: "KJHUIKit-iOS",
		    clean: true,
		    build: true
	  	)
	end
end
